plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id

tasks.named('jar', Jar) {
    archiveBaseName.set('tdrss')
    archiveVersion.set(mod_version)
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version
    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
    runs {
        client { client(); systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id }
        server { server(); systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id; programArgument '--nogui' }
        gameTestServer { type = "gameTestServer"; systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id }
        data { data(); programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath() }
        configureEach { systemProperty 'forge.logging.markers', 'REGISTRIES'; logLevel = org.slf4j.event.Level.DEBUG }
    }
    mods { "${mod_id}" { sourceSet sourceSets.main } }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "ManasMods"
        url = "https://nexus.nighti.dev/repository/manasmods-public/"
    }
    maven { url = 'https://maven.architectury.dev/' }
    maven { url = 'https://maven.shedaniel.me/' }
}

dependencies {
    compileOnly files('libs/tensura-neoforge-2.0.1.0.jar')

    compileOnly "io.github.manasmods:manascore-race-neoforge:${manascore_version}"
    compileOnly "io.github.manasmods:manascore-storage-neoforge:${manascore_version}"
    compileOnly "io.github.manasmods:manascore-config-neoforge:${manascore_version}"
    compileOnly "io.github.manasmods:manascore-network-neoforge:${manascore_version}"
}

processResources {
    inputs.property 'mod_id', mod_id
    inputs.property 'mod_name', mod_name
    inputs.property 'mod_version', mod_version
    inputs.property 'mod_authors', mod_authors
    inputs.property 'mod_description', mod_description
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) { expand inputs.properties }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
